openapi: 3.0.0
info:
  title: Task API
  version: 1.0.0
  description: API for managing tasks

paths:
  /tasks:
    get:
      summary: Retrieve all tasks
      tags: [Task]
      responses:
        200:
          description: A list of tasks
    post:
      summary: Create a new task
      tags: [Task]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
      responses:
        201:
          description: Task created

  /tasks/{id}:
    get:
      summary: Retrieve a task by ID
      tags: [Task]
      parameters:
        - name: id
          in: path
          required: true
          description: Task ID
      responses:
        200:
          description: Task found
        404:
          description: Task not found
    put:
      summary: Update an existing task
      tags: [Task]
      parameters:
        - name: id
          in: path
          required: true
          description: Task ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
      responses:
        200:
          description: Task updated
    delete:
      summary: Delete a task by ID
      tags: [Task]
      parameters:
        - name: id
          in: path
          required: true
          description: Task ID
      responses:
        204:
          description: Task deleted
